### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by Anjacodes** [williamrolando88/ultimate-show-guide#25]
Congratulations William, your code is very nice and structured and looks beautiful.
Some suggestions:

* Reconsider if you need to map over the array as all this looping might be slowing down performance
* Since the project is small and simple, there might be an easier solution
* The page is loading quite slow so think about whether this can be optimized.

**Comment by keroloussamy** [comment]
Thanks, @Anjacodes for the Issue, and very good structure @williamrolando88. Keep it up. 🔥🔥
